version: "2"
services:
  chrome:
    image: selenium/standalone-chrome-debug
    container_name: chrome
    ports:
      - "4444:4444"
      - "5900:5900"
  firefox:
    image: selenium/standalone-firefox-debug
    container_name: firefox
    ports:
      - "4444:4445"
      - "5900:5901"
  calendar:
    build:
      context: ./docker
      dockerfile: calendar_dockerfile
    container_name: calendar
    ports:
      - "8000:8000"